version: 2
cli:
  server: https://app.fossa.com
  fetcher: custom
  project: git@github.com:SDA-SE/sda-spring-boot-commoms.git
analyze:
  modules:
    - name: .
      type: gradle
      target: ':'
      path: .
      options:
        online: true
