# Name of the site, displayed in the navigation

site_name: sda-spring-boot-commons

# To display a page inside the navigation you must include them here

# These files are relative to the /docs repository

# Learn more on <https://www.mkdocs.org/user-guide/writing-your-docs/>

nav:
  - Overview: index.md
  - Starter Web: starter-web.md
  - Starter MongoDB: starter-mongodb.md
  - Starter Kafka: starter-kafka.md
  - Starter S3: starter-s3.md
  - Starter MCP: starter-mcp.md
  - Security Hardening: security.md
  - AsyncAPI: asyncapi.md
  - Cloud Events: cloudevents.md
  - Metadata Context: metadata-context.md
  - Testing: web-testing.md
  - Migration:
    - Migrate to v3: migration-2-to-3.md
    - Migrate to v4: migration-3-to-4.md
    - Migrate to v5: migration-4-to-5.md

# Always include the techdocs-core plugin, otherwise it's not possible to
# display the documentation in Backstage. We don't support other plugins

plugins:
  - techdocs-core

markdown_extensions:
  # Add support for the `--8<--` feature to import files. Remove this as soon as it is
  # part of the techdocs-core plugin: https://github.com/backstage/mkdocs-techdocs-core/issues/20
  - pymdownx.snippets
