openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /cars:
    get:
      operationId: getCars
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Cars"
          description: A successful response
        "404":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiError"
          description: Resource not found
      tags:
      - app
  /trees:
    get:
      operationId: getTrees
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Trees"
          description: A successful response
        "404":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiError"
          description: Resource not found
      tags:
      - app
components:
  schemas:
    ApiError:
      type: object
      description: Describes an api error object to transfer error information between
        server and client.
      properties:
        invalidParams:
          type: array
          description: Contains a list of invalid parameters in case of validation
            errors. Parameters in this case can be for example fields in a Json of
            the request body or query params.
          example: []
          items:
            $ref: "#/components/schemas/ApiInvalidParam"
        title:
          type: string
          description: The human readable description of the error.
          example: Request parameters are not valid
    ApiInvalidParam:
      type: object
      description: Defines a validation error for a parameter or field.
      example: []
      properties:
        errorCode:
          type: string
          description: "The name of the validation annotation given in uppercase,\
            \ underscore notation."
          example: FIELD_CORRELATION_ERROR
        field:
          type: string
          description: The name or path of the invalid field or parameter.
          example: manufacture
        reason:
          type: string
          description: Gives a hint why the value is not valid. This is the error
            message of the validation. The reason might be in different language due
            to internationalization.
          example: Audi has no Golf GTI model (not found)
    Car:
      type: object
      description: A car
      properties:
        licensePlate:
          type: string
          description: The license plate
    Cars:
      type: object
      description: A list of cars
      properties:
        cars:
          type: array
          description: The cars
          items:
            $ref: "#/components/schemas/Car"
    Tree:
      type: object
      description: A tree
      properties:
        name:
          type: string
          description: The name
    Trees:
      type: object
      description: A list of trees
      properties:
        trees:
          type: array
          description: The trees
          items:
            $ref: "#/components/schemas/Tree"
