openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /cars:
    get:
      tags:
      - app
      operationId: getCars
      responses:
        "200":
          description: A successful response
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Cars"
        "404":
          description: Resource not found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiError"
  /trees:
    get:
      tags:
      - app
      operationId: getTrees
      responses:
        "200":
          description: A successful response
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Trees"
        "404":
          description: Resource not found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiError"
components:
  schemas:
    ApiError:
      type: object
      properties:
        invalidParams:
          type: array
          description: Contains a list of invalid parameters in case of validation
            errors. Parameters in this case can be for example fields in a Json of
            the request body or query params.
          example: []
          items:
            $ref: "#/components/schemas/ApiInvalidParam"
        title:
          type: string
          description: The human readable description of the error.
          example: Request parameters are not valid
      description: Describes an api error object to transfer error information between
        server and client.
    ApiInvalidParam:
      type: object
      properties:
        errorCode:
          type: string
          description: "The name of the validation annotation given in uppercase,\
            \ underscore notation."
          example: FIELD_CORRELATION_ERROR
        field:
          type: string
          description: The name or path of the invalid field or parameter.
          example: manufacture
        reason:
          type: string
          description: Gives a hint why the value is not valid. This is the error
            message of the validation. The reason might be in different language due
            to internationalization.
          example: Audi has no Golf GTI model (not found)
      description: Defines a validation error for a parameter or field.
      example: []
    Car:
      type: object
      properties:
        licensePlate:
          type: string
          description: The license plate
      description: A car
    Cars:
      type: object
      properties:
        cars:
          type: array
          description: The cars
          items:
            $ref: "#/components/schemas/Car"
      description: A list of cars
    Tree:
      type: object
      properties:
        name:
          type: string
          description: The name
      description: A tree
    Trees:
      type: object
      properties:
        trees:
          type: array
          description: The trees
          items:
            $ref: "#/components/schemas/Tree"
      description: A list of trees
