name: Publish mkdocs
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2
        with:
          fetch-depth: 1
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - run: sudo apt-get update && sudo apt-get -yq install graphviz git fonts-ipafont fonts-ipaexfont
      - run: >
          wget -q -O /usr/local/bin/plantuml https://github.com/mikaelhg/puni2/releases/download/1.2022.7/plantuml-1.2022.7-glibc-x86_64
          && chmod 755 /usr/local/bin/plantuml
      - uses: actions/setup-python@c4e89fac7e8767b327bbad6cb4d859eda999cf08 #v.4.1.0
        with:
          python-version: 3.x
      - run: pip install mkdocs-techdocs-core # Includes material theme
      - run: pip install mkdocs-build-plantuml-plugin
      - run: git fetch origin gh-pages # Get latest history
      - run: > # required for mkdocs, not for techdocs
          yq -i '.plugins |= . +
          [{"build_plantuml": {"render":"server", "server":"http://www.plantuml.com/plantuml", "output_format": "svg"}}]'
          mkdocs.yaml
      - name: Dry run generated mkdocs
        if: github.event_name == 'pull_request'
        run: mkdocs build --config-file mkdocs.yaml && ls -al
      - name: Archive test build
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: site
          path: |
            site
          retention-days: 1
      - name: Publish generated mkdocs
        if: github.event_name != 'pull_request'
        run: mkdocs gh-deploy --config-file mkdocs.yaml
