name: Publish release

on:
  release:
    types:
      - released
      - prereleased

env:
  SEMANTIC_VERSION: ${{ github.event.release.tag_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'gradle'

      - name: Build and Publish Snapshot
        run: ./gradlew publishMavenPublicationToSdaInternRepository
        env:
          SDA_NEXUS_USER: ${{ secrets.NEXUS_LOGIN_USER }} # Update gh secrets to TU
          SDA_NEXUS_PASSWORD: ${{ secrets.NEXUS_LOGIN_PASSWORD }}