name: Publish release

on:
  release:
    types:
      - released
      - prereleased

env:
  SEMANTIC_VERSION: ${{ github.event.release.tag_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'


      - name: Build and Sign packages
        run: ./gradlew --parallel signMavenPublication
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PRIVATE_KEY_SECRET }}

      - name: Publish to Sda Intern Nexus
        run: ./gradlew -x signMavenPublication publishMavenPublicationToSdaInternRepository
        env:
          SDA_NEXUS_USER: ${{ secrets.NEXUS_LOGIN_USER }}
          SDA_NEXUS_PASSWORD: ${{ secrets.NEXUS_LOGIN_PASSWORD }}
