# This workflow uploads snapshots of Pull Requests
name: Pull Request Snapshots

on: [pull_request]

env:
  SEMANTIC_VERSION: PR-${{ github.event.number }}-SNAPSHOT

jobs:
  pull-request-snapshots:
    # do not execute for PRs that origin from forks or created by dependabot since we are missing the secrets for the push
    if: "!(github.event.pull_request && github.event.pull_request.head.repo.fork) && github.actor != 'dependabot[bot]'"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # tag=v3
      - name: Set up JDK 17
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Build and Sign packages
        run: ./gradlew --parallel signMavenPublication
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PRIVATE_KEY_SECRET }}

      - name: Publish Snapshot
        run: ./gradlew -x signMavenPublication publishMavenPublicationToSdaInternRepository
        env:
          SDA_NEXUS_USER: ${{ secrets.NEXUS_LOGIN_USER }}
          SDA_NEXUS_PASSWORD: ${{ secrets.NEXUS_LOGIN_PASSWORD }}
