# This workflow uploads snapshots of Pull Requests
name: Pull Request Snapshots

on: [pull_request]

jobs:
  pull-request-snapshots:
    # do not execute for PRs that origin from forks or created by dependabot since we are missing the secrets for the push
    if: "!(github.event.pull_request && github.event.pull_request.head.repo.fork) && github.actor != 'dependabot[bot]'"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Build and Publish Snapshot
        run: ./gradlew publishMavenPublicationToSdaInternRepository
        env:
          SEMANTIC_VERSION: PR-${{ github.event.number }}-SNAPSHOT
          SDA_NEXUS_USER: ${{ secrets.NEXUS_LOGIN_USER }}
          SDA_NEXUS_PASSWORD: ${{ secrets.GH_PUBLISH_TOKEN }}
