spring:
  data:
    mongodb:
      authentication-database: "admin"
        hosts: "${MONGODB_HOSTS}"
        database: "${MONGODB_DATABASE:-}"
        username: "${MONGODB_USERNAME:-}"
        password: "${MONGODB_PASSWORD:-}"
        options: "${MONGODB_OPTIONS}"
        useSsl: ${MONGODB_USE_SSL:-true}
        caCertificate: "${MONGODB_CA_CERTIFICATE:-}"
        auto-index-creation: !!bool true

management:
  endpoints:
    web:
      exposure:
        include: "env", "health", "metrics"
       #include: "*"

